# Generated by Django 3.2.8 on 2021-10-20 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following_user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='which_user',
        ),
        migrations.AddField(
            model_name='follow',
            name='given_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='requested_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
