# Generated by Django 3.2.8 on 2021-10-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211020_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='rejected',
        ),
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='requested', max_length=40),
        ),
    ]
